//
//  StackOverFlowStyleKit.m
//  ProjectName
//
//  Created by jnagel on 5/12/15.
//  Copyright (c) 2015 . All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import "StackOverFlowStyleKit.h"


@implementation StackOverFlowStyleKit

#pragma mark Cache

static UIColor* _orange = nil;
static UIColor* _lightGray = nil;

#pragma mark Initialization

+ (void)initialize
{
    // Colors Initialization
    _orange = [UIColor colorWithRed: 1 green: 0.6 blue: 0 alpha: 1];
    _lightGray = [UIColor colorWithRed: 0.847 green: 0.847 blue: 0.847 alpha: 1];

}

#pragma mark Colors

+ (UIColor*)orange { return _orange; }
+ (UIColor*)lightGray { return _lightGray; }

#pragma mark Drawing Methods

+ (void)drawCanvas1
{
}

@end
