//
//  StackOverFlowStyleKit.h
//  ProjectName
//
//  Created by jnagel on 5/12/15.
//  Copyright (c) 2015 . All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface StackOverFlowStyleKit : NSObject

// Colors
+ (UIColor*)orange;
+ (UIColor*)lightGray;

// Drawing Methods
+ (void)drawCanvas1;

@end
